import type { Recipe } from "./types";

// ============================================================
// Bousti — Lot étendu de recettes ORIGINALES (rédigées maison).
// Les plats sont des classiques du domaine public ; les textes,
// quantités et prix sont écrits pour Bousti. Chaque recette est
// signée d'un prénom de cuisinier. Prix : € par unité de base.
// ============================================================

export const EXTRA_RECIPES: Recipe[] = [
  // -------------------- Petit-déj & brunch --------------------
  {
    id: "porridge-avoine",
    name: "Porridge avoine banane",
    cookName: "Élodie",
    emoji: "🥣",
    moments: ["petit-dej", "brunch"],
    level: 1,
    timeMin: 10,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["healthy", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Chauffer les flocons d'avoine avec le lait en remuant.",
      "Laisser épaissir 5 min à feu doux.",
      "Ajouter la banane en rondelles et un filet de miel.",
    ],
    ingredients: [
      { name: "Flocons d'avoine", qtyPerPerson: 50, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.003 },
      { name: "Lait", qtyPerPerson: 200, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Banane", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Miel", qtyPerPerson: 10, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.008 },
    ],
  },
  {
    id: "shakshuka",
    name: "Shakshuka œufs pochés à la tomate",
    cookName: "Yara",
    emoji: "🍳",
    moments: ["brunch", "dejeuner", "diner"],
    level: 2,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf"],
    tags: ["oriental", "epice", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Faire compoter poivron, oignon et tomates avec cumin et paprika.",
      "Creuser des puits et y casser les œufs.",
      "Couvrir et cuire jusqu'à ce que les blancs prennent.",
    ],
    ingredients: [
      { name: "Œuf", qtyPerPerson: 2, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Tomates concassées", qtyPerPerson: 150, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "pain-perdu",
    name: "Pain perdu vanillé",
    cookName: "Mamie Jeanne",
    emoji: "🍞",
    moments: ["petit-dej", "gouter", "dessert"],
    level: 1,
    timeMin: 15,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "gourmand", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Battre œufs, lait et sucre vanillé.",
      "Tremper les tranches de pain rassis.",
      "Dorer à la poêle beurrée des deux côtés.",
    ],
    ingredients: [
      { name: "Pain de campagne", qtyPerPerson: 90, unit: "g", aisle: "Boulangerie", unitPrice: 0.004 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Lait", qtyPerPerson: 80, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Sucre", qtyPerPerson: 15, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
    ],
  },
  // -------------------- Apéro & afterwork --------------------
  {
    id: "bruschetta",
    name: "Bruschetta tomate-basilic",
    cookName: "Enzo",
    emoji: "🍅",
    moments: ["apero", "afterwork"],
    level: 1,
    timeMin: 12,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: ["gluten"],
    tags: ["italien", "healthy"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Toaster les tranches de pain, frotter à l'ail.",
      "Mélanger tomates en dés, huile d'olive et basilic.",
      "Garnir le pain juste avant de servir.",
    ],
    ingredients: [
      { name: "Baguette", qtyPerPerson: 0.4, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.95 },
      { name: "Tomate", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Basilic", qtyPerPerson: 4, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.06 },
    ],
  },
  {
    id: "cake-sale",
    name: "Cake salé olives-jambon",
    cookName: "Sylvie",
    emoji: "🫒",
    moments: ["apero", "afterwork", "dejeuner"],
    level: 2,
    timeMin: 50,
    equipment: ["four"],
    isMeat: true,
    isFish: false,
    hasPork: true,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Mélanger farine, levure, œufs, huile et lait.",
      "Ajouter jambon en dés, olives et fromage.",
      "Cuire 40 min à 180°C dans un moule à cake.",
    ],
    ingredients: [
      { name: "Farine", qtyPerPerson: 40, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Œuf", qtyPerPerson: 0.75, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Jambon", qtyPerPerson: 0.6, unit: "pièce", aisle: "Boucherie & poissonnerie", unitPrice: 0.7 },
      { name: "Olives", qtyPerPerson: 25, unit: "g", aisle: "Épicerie salée", unitPrice: 0.01 },
      { name: "Fromage râpé", qtyPerPerson: 30, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
    ],
  },
  {
    id: "gougeres",
    name: "Gougères au comté",
    cookName: "Bernard",
    emoji: "🧀",
    moments: ["apero", "afterwork"],
    level: 3,
    timeMin: 40,
    equipment: ["four", "casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Réaliser une pâte à choux (eau, beurre, farine, œufs).",
      "Incorporer le comté râpé.",
      "Dresser en petits tas et cuire 25 min à 190°C.",
    ],
    ingredients: [
      { name: "Farine", qtyPerPerson: 35, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Beurre", qtyPerPerson: 25, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Comté râpé", qtyPerPerson: 35, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.025 },
    ],
  },

  // -------------------- Salades & entrées --------------------
  {
    id: "salade-grecque",
    name: "Salade grecque feta-olives",
    cookName: "Eleni",
    emoji: "🥗",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 12,
    equipment: [],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["healthy", "oriental"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Couper concombre, tomates et oignon rouge.",
      "Ajouter feta en cubes et olives.",
      "Assaisonner huile d'olive, origan et citron.",
    ],
    ingredients: [
      { name: "Concombre", qtyPerPerson: 0.4, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Tomate", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Feta", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
      { name: "Olives", qtyPerPerson: 30, unit: "g", aisle: "Épicerie salée", unitPrice: 0.01 },
      { name: "Oignon rouge", qtyPerPerson: 0.25, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.4 },
    ],
  },
  {
    id: "taboule",
    name: "Taboulé semoule-menthe",
    cookName: "Nadia",
    emoji: "🌿",
    moments: ["dejeuner", "apero", "afterwork"],
    level: 1,
    timeMin: 15,
    equipment: [],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: ["gluten"],
    tags: ["oriental", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Hydrater la semoule avec de l'eau tiède et du citron.",
      "Ajouter tomates, concombre, menthe et persil.",
      "Arroser d'huile d'olive et laisser reposer au frais.",
    ],
    ingredients: [
      { name: "Semoule", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.0022 },
      { name: "Tomate", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Concombre", qtyPerPerson: 0.25, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Citron", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
    ],
  },
  {
    id: "gaspacho",
    name: "Gaspacho andalou",
    cookName: "Lucia",
    emoji: "🍅",
    moments: ["dejeuner", "diner", "apero"],
    level: 1,
    timeMin: 15,
    equipment: ["robot"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["healthy", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Mixer tomates, concombre, poivron et ail.",
      "Émulsionner avec huile d'olive et vinaigre.",
      "Servir bien frais.",
    ],
    ingredients: [
      { name: "Tomate", qtyPerPerson: 2, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Concombre", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Poivron", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
    ],
  },
  {
    id: "salade-chevre-chaud",
    name: "Salade de chèvre chaud",
    cookName: "Hélène",
    emoji: "🐐",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 15,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["francais", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Poser les crottins sur des tranches de pain, gratiner au four.",
      "Dresser la salade avec noix et miel.",
      "Ajouter les toasts chauds et la vinaigrette.",
    ],
    ingredients: [
      { name: "Fromage de chèvre", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.014 },
      { name: "Salade", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 1.1 },
      { name: "Baguette", qtyPerPerson: 0.25, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.95 },
      { name: "Miel", qtyPerPerson: 8, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.008 },
    ],
  },

  // -------------------- Plats viande --------------------
  {
    id: "bolognaise",
    name: "Spaghetti bolognaise",
    cookName: "Giulia",
    emoji: "🍝",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 40,
    equipment: ["casserole", "poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten"],
    tags: ["italien", "reconfort", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Faire revenir oignon, carotte et bœuf haché.",
      "Ajouter tomates et laisser mijoter 25 min.",
      "Servir sur les spaghetti cuits al dente.",
    ],
    ingredients: [
      { name: "Spaghetti", qtyPerPerson: 110, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.0018 },
      { name: "Steak haché de bœuf", qtyPerPerson: 100, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.013 },
      { name: "Tomates concassées", qtyPerPerson: 120, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Carotte", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "lasagnes",
    name: "Lasagnes à la bolognaise",
    cookName: "Paolo",
    emoji: "🍲",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 60,
    equipment: ["four", "casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["italien", "reconfort", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Préparer une sauce bolognaise et une béchamel.",
      "Alterner plaques, sauce, béchamel et fromage.",
      "Enfourner 35 min à 180°C.",
    ],
    ingredients: [
      { name: "Plaques de lasagne", qtyPerPerson: 90, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.003 },
      { name: "Steak haché de bœuf", qtyPerPerson: 90, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.013 },
      { name: "Tomates concassées", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Lait", qtyPerPerson: 80, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Fromage râpé", qtyPerPerson: 40, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
    ],
  },
  {
    id: "hachis-parmentier",
    name: "Hachis parmentier",
    cookName: "Julien",
    emoji: "🥔",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 50,
    equipment: ["four", "casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["francais", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Écraser les pommes de terre en purée avec du lait.",
      "Étaler la viande hachée revenue avec oignon au fond du plat.",
      "Couvrir de purée, gratiner 20 min à 190°C.",
    ],
    ingredients: [
      { name: "Pomme de terre", qtyPerPerson: 250, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
      { name: "Steak haché de bœuf", qtyPerPerson: 100, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.013 },
      { name: "Lait", qtyPerPerson: 60, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "poulet-roti",
    name: "Poulet rôti pommes grenaille",
    cookName: "Bernard",
    emoji: "🍗",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 80,
    equipment: ["four"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: [],
    tags: ["francais", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Badigeonner le poulet d'huile, sel, thym.",
      "Disposer les pommes grenaille autour.",
      "Rôtir 1 h à 200°C en arrosant.",
    ],
    ingredients: [
      { name: "Cuisse de poulet", qtyPerPerson: 1, unit: "pièce", aisle: "Boucherie & poissonnerie", unitPrice: 1.6 },
      { name: "Pomme de terre", qtyPerPerson: 200, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
    ],
  },
  {
    id: "chili-con-carne",
    name: "Chili con carne",
    cookName: "Diego",
    emoji: "🌶️",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 40,
    equipment: ["casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: [],
    tags: ["mexicain", "epice", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Revenir bœuf haché, oignon et ail.",
      "Ajouter haricots rouges, tomates, maïs et épices.",
      "Mijoter 25 min, servir avec du riz.",
    ],
    ingredients: [
      { name: "Steak haché de bœuf", qtyPerPerson: 100, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.013 },
      { name: "Haricots rouges", qtyPerPerson: 90, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Tomates concassées", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Riz", qtyPerPerson: 60, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
    ],
  },
  {
    id: "couscous-poulet",
    name: "Couscous poulet-légumes",
    cookName: "Karim",
    emoji: "🍲",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 55,
    equipment: ["casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten"],
    tags: ["oriental", "reconfort", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Mijoter poulet, carottes, courgettes et pois chiches aux épices.",
      "Cuire la semoule à la vapeur.",
      "Servir la semoule nappée de bouillon et légumes.",
    ],
    ingredients: [
      { name: "Cuisse de poulet", qtyPerPerson: 0.8, unit: "pièce", aisle: "Boucherie & poissonnerie", unitPrice: 1.6 },
      { name: "Semoule", qtyPerPerson: 80, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.0022 },
      { name: "Carotte", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Courgette", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.7 },
      { name: "Pois chiches", qtyPerPerson: 50, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
    ],
  },
  {
    id: "escalope-milanaise",
    name: "Escalope milanaise",
    cookName: "Giulia",
    emoji: "🍖",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "oeuf"],
    tags: ["italien", "gourmand", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Paner les escalopes (farine, œuf, chapelure).",
      "Frire à la poêle jusqu'à coloration dorée.",
      "Servir avec un filet de citron.",
    ],
    ingredients: [
      { name: "Escalope de poulet", qtyPerPerson: 130, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.012 },
      { name: "Chapelure", qtyPerPerson: 30, unit: "g", aisle: "Épicerie salée", unitPrice: 0.004 },
      { name: "Œuf", qtyPerPerson: 0.5, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
    ],
  },
  {
    id: "boulettes-tomate",
    name: "Boulettes de bœuf sauce tomate",
    cookName: "Marc",
    emoji: "🍖",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 35,
    equipment: ["poele", "casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "oeuf"],
    tags: ["italien", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Former des boulettes (bœuf, chapelure, œuf, herbes).",
      "Les dorer puis les mijoter dans la sauce tomate.",
      "Servir avec des pâtes.",
    ],
    ingredients: [
      { name: "Steak haché de bœuf", qtyPerPerson: 110, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.013 },
      { name: "Tomates concassées", qtyPerPerson: 120, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Pâtes", qtyPerPerson: 90, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.0018 },
      { name: "Chapelure", qtyPerPerson: 15, unit: "g", aisle: "Épicerie salée", unitPrice: 0.004 },
    ],
  },
  {
    id: "saucisse-lentilles",
    name: "Saucisses & lentilles",
    cookName: "Sylvie",
    emoji: "🌭",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 40,
    equipment: ["casserole"],
    isMeat: true,
    isFish: false,
    hasPork: true,
    isVegan: false,
    allergens: [],
    tags: ["francais", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Faire revenir oignon, carotte et lardons.",
      "Ajouter lentilles vertes et eau, cuire 25 min.",
      "Poser les saucisses grillées dessus.",
    ],
    ingredients: [
      { name: "Saucisse", qtyPerPerson: 1, unit: "pièce", aisle: "Boucherie & poissonnerie", unitPrice: 0.9 },
      { name: "Lentilles vertes", qtyPerPerson: 80, unit: "g", aisle: "Épicerie salée", unitPrice: 0.004 },
      { name: "Carotte", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "cordon-bleu-puree",
    name: "Cordon bleu & purée maison",
    cookName: "Chloé",
    emoji: "🍗",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 30,
    equipment: ["poele", "casserole"],
    isMeat: true,
    isFish: false,
    hasPork: true,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Cuire les cordons bleus à la poêle.",
      "Écraser les pommes de terre avec lait et beurre.",
      "Servir bien chaud.",
    ],
    ingredients: [
      { name: "Cordon bleu", qtyPerPerson: 1, unit: "pièce", aisle: "Boucherie & poissonnerie", unitPrice: 1.3 },
      { name: "Pomme de terre", qtyPerPerson: 200, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
      { name: "Lait", qtyPerPerson: 50, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Beurre", qtyPerPerson: 15, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
    ],
  },

  // -------------------- Plats poisson --------------------
  {
    id: "cabillaud-citron",
    name: "Cabillaud beurre citronné",
    cookName: "Hélène",
    emoji: "🐟",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: false,
    isFish: true,
    hasPork: false,
    isVegan: false,
    allergens: ["poisson", "lactose"],
    tags: ["healthy", "francais"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Poêler le dos de cabillaud à feu doux.",
      "Déglacer au citron et monter au beurre.",
      "Servir avec du riz.",
    ],
    ingredients: [
      { name: "Dos de cabillaud", qtyPerPerson: 130, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.02 },
      { name: "Citron", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
      { name: "Riz", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Beurre", qtyPerPerson: 15, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
    ],
  },
  {
    id: "moules-frites",
    name: "Moules marinières & frites",
    cookName: "Julien",
    emoji: "🦪",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 30,
    equipment: ["casserole", "four"],
    isMeat: false,
    isFish: true,
    hasPork: false,
    isVegan: false,
    allergens: ["fruits-de-mer"],
    tags: ["francais", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Faire ouvrir les moules avec échalote, vin blanc et persil.",
      "Cuire les frites au four.",
      "Servir aussitôt.",
    ],
    ingredients: [
      { name: "Moules", qtyPerPerson: 400, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.005 },
      { name: "Frites surgelées", qtyPerPerson: 150, unit: "g", aisle: "Surgelés", unitPrice: 0.003 },
      { name: "Échalote", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.25 },
    ],
  },
  {
    id: "fish-and-chips",
    name: "Fish and chips",
    cookName: "Tom",
    emoji: "🍟",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 2,
    timeMin: 35,
    equipment: ["poele", "four"],
    isMeat: false,
    isFish: true,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "poisson"],
    tags: ["street-food", "gourmand", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Enrober le poisson d'une pâte à beignet.",
      "Frire jusqu'à ce que ce soit doré.",
      "Servir avec des frites au four.",
    ],
    ingredients: [
      { name: "Dos de cabillaud", qtyPerPerson: 130, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.02 },
      { name: "Frites surgelées", qtyPerPerson: 150, unit: "g", aisle: "Surgelés", unitPrice: 0.003 },
      { name: "Farine", qtyPerPerson: 40, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
    ],
  },
  {
    id: "bo-bun",
    name: "Bo bun bœuf-citronnelle",
    cookName: "Malee",
    emoji: "🍜",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 30,
    equipment: ["poele", "casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["soja", "arachide"],
    tags: ["asiatique", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Cuire les vermicelles de riz.",
      "Sauter le bœuf mariné à la citronnelle.",
      "Dresser vermicelles, crudités, bœuf, cacahuètes et sauce.",
    ],
    ingredients: [
      { name: "Bœuf émincé", qtyPerPerson: 110, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.016 },
      { name: "Vermicelles de riz", qtyPerPerson: 80, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.004 },
      { name: "Carotte", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Cacahuètes", qtyPerPerson: 15, unit: "g", aisle: "Épicerie salée", unitPrice: 0.008 },
    ],
  },

  // -------------------- Végé & vegan --------------------
  {
    id: "ratatouille",
    name: "Ratatouille provençale",
    cookName: "Manon",
    emoji: "🍆",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 45,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["francais", "healthy", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Couper aubergine, courgette, poivron et tomates.",
      "Faire fondre doucement avec ail et herbes de Provence.",
      "Mijoter 30 min à couvert.",
    ],
    ingredients: [
      { name: "Aubergine", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.9 },
      { name: "Courgette", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.7 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Tomate", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
    ],
  },
  {
    id: "gnocchi-tomate",
    name: "Gnocchi sauce tomate-basilic",
    cookName: "Enzo",
    emoji: "🥔",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 15,
    equipment: ["casserole", "poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["italien", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Poêler les gnocchi jusqu'à coloration.",
      "Ajouter la sauce tomate et le basilic.",
      "Parsemer de parmesan.",
    ],
    ingredients: [
      { name: "Gnocchi", qtyPerPerson: 200, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.004 },
      { name: "Sauce tomate", qtyPerPerson: 80, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Parmesan râpé", qtyPerPerson: 15, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.035 },
    ],
  },
  {
    id: "pates-pesto",
    name: "Pâtes au pesto",
    cookName: "Camille",
    emoji: "🌿",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 15,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "fruits-a-coque"],
    tags: ["italien", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Cuire les pâtes al dente.",
      "Mélanger avec le pesto hors du feu.",
      "Ajouter un peu d'eau de cuisson et du parmesan.",
    ],
    ingredients: [
      { name: "Pâtes", qtyPerPerson: 110, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.0018 },
      { name: "Pesto", qtyPerPerson: 40, unit: "g", aisle: "Épicerie salée", unitPrice: 0.012 },
      { name: "Parmesan râpé", qtyPerPerson: 15, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.035 },
    ],
  },
  {
    id: "parmigiana",
    name: "Parmigiana d'aubergines",
    cookName: "Paolo",
    emoji: "🍆",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 60,
    equipment: ["four", "poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["italien", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Dorer les tranches d'aubergine.",
      "Alterner aubergine, sauce tomate et mozzarella.",
      "Gratiner 30 min à 180°C.",
    ],
    ingredients: [
      { name: "Aubergine", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.9 },
      { name: "Sauce tomate", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Mozzarella", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
      { name: "Parmesan râpé", qtyPerPerson: 20, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.035 },
    ],
  },
  {
    id: "omelette-fromage",
    name: "Omelette au fromage",
    cookName: "Tom",
    emoji: "🍳",
    moments: ["dejeuner", "diner", "brunch"],
    level: 1,
    timeMin: 10,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf", "lactose"],
    tags: ["francais", "reconfort", "healthy"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Battre les œufs, saler et poivrer.",
      "Cuire à la poêle beurrée.",
      "Ajouter le fromage râpé et plier.",
    ],
    ingredients: [
      { name: "Œuf", qtyPerPerson: 3, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Fromage râpé", qtyPerPerson: 40, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
    ],
  },
  {
    id: "galette-sarrasin",
    name: "Galette de sarrasin œuf-fromage",
    cookName: "Erwan",
    emoji: "🥞",
    moments: ["dejeuner", "diner", "brunch"],
    level: 2,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf", "lactose"],
    tags: ["francais", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Étaler la pâte à galette sur la poêle chaude.",
      "Casser un œuf au centre, ajouter le fromage.",
      "Replier les bords et servir.",
    ],
    ingredients: [
      { name: "Farine de sarrasin", qtyPerPerson: 60, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.003 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Fromage râpé", qtyPerPerson: 40, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
    ],
  },
  {
    id: "soupe-legumes",
    name: "Soupe de légumes maison",
    cookName: "Sylvie",
    emoji: "🥕",
    moments: ["diner"],
    level: 1,
    timeMin: 35,
    equipment: ["casserole", "robot"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["healthy", "reconfort", "francais"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Éplucher et couper poireau, carotte et pomme de terre.",
      "Cuire dans l'eau 25 min.",
      "Mixer jusqu'à consistance lisse.",
    ],
    ingredients: [
      { name: "Poireau", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.6 },
      { name: "Carotte", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Pomme de terre", qtyPerPerson: 120, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
    ],
  },
  {
    id: "riz-cantonais-vege",
    name: "Riz cantonais végétarien",
    cookName: "Malee",
    emoji: "🍚",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 20,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf", "soja"],
    tags: ["asiatique", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Sauter le riz cuit avec petits pois et carottes.",
      "Ajouter l'œuf brouillé.",
      "Assaisonner à la sauce soja.",
    ],
    ingredients: [
      { name: "Riz", qtyPerPerson: 80, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Petits pois", qtyPerPerson: 50, unit: "g", aisle: "Surgelés", unitPrice: 0.004 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Carotte", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
    ],
  },
  {
    id: "curry-pois-chiches",
    name: "Curry de pois chiches épinards",
    cookName: "Priya",
    emoji: "🍛",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 25,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["indien", "healthy", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Faire revenir oignon, ail, gingembre et épices.",
      "Ajouter pois chiches, tomates et épinards.",
      "Mijoter 15 min, servir avec du riz.",
    ],
    ingredients: [
      { name: "Pois chiches", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Épinards", qtyPerPerson: 80, unit: "g", aisle: "Surgelés", unitPrice: 0.004 },
      { name: "Tomates concassées", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Riz basmati", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
    ],
  },

  // -------------------- Cuisine du monde --------------------
  {
    id: "butter-chicken",
    name: "Butter chicken",
    cookName: "Aarav",
    emoji: "🍗",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 40,
    equipment: ["poele", "casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["indien", "epice", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Mariner le poulet au yaourt et épices, le saisir.",
      "Préparer une sauce tomate-crème au garam masala.",
      "Mijoter le poulet dedans, servir avec du riz.",
    ],
    ingredients: [
      { name: "Filet de poulet", qtyPerPerson: 130, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Tomates concassées", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Crème fraîche", qtyPerPerson: 40, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.006 },
      { name: "Riz basmati", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
    ],
  },
  {
    id: "fajitas-poulet",
    name: "Fajitas de poulet",
    cookName: "Diego",
    emoji: "🌯",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 1,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten"],
    tags: ["mexicain", "street-food", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Sauter poulet, poivrons et oignons aux épices tex-mex.",
      "Réchauffer les tortillas.",
      "Garnir et rouler.",
    ],
    ingredients: [
      { name: "Filet de poulet", qtyPerPerson: 120, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Tortillas de blé", qtyPerPerson: 2, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.3 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "ramen-poulet",
    name: "Ramen express au poulet",
    cookName: "Kenji",
    emoji: "🍜",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 30,
    equipment: ["casserole"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "oeuf", "soja"],
    tags: ["asiatique", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Chauffer un bouillon miso-soja avec gingembre.",
      "Cuire les nouilles et pocher un œuf mollet.",
      "Dresser bouillon, nouilles, poulet, œuf et oignon vert.",
    ],
    ingredients: [
      { name: "Nouilles ramen", qtyPerPerson: 90, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.004 },
      { name: "Filet de poulet", qtyPerPerson: 90, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Bouillon de légumes", qtyPerPerson: 350, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.0008 },
    ],
  },
  {
    id: "bibimbap",
    name: "Bibimbap végétarien",
    cookName: "Kenji",
    emoji: "🍲",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 35,
    equipment: ["poele", "casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf", "soja", "sesame"],
    tags: ["asiatique", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Cuire le riz et préparer les légumes séparément.",
      "Poêler carotte, courgette et champignons.",
      "Dresser sur le riz avec un œuf au plat et sauce.",
    ],
    ingredients: [
      { name: "Riz rond", qtyPerPerson: 80, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Carotte", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Courgette", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.7 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Champignons de Paris", qtyPerPerson: 60, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.005 },
    ],
  },
  {
    id: "shawarma-poulet",
    name: "Shawarma de poulet",
    cookName: "Yassine",
    emoji: "🌯",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 1,
    timeMin: 30,
    equipment: ["poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "sesame"],
    tags: ["oriental", "street-food", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Mariner et poêler le poulet aux épices shawarma.",
      "Préparer une sauce yaourt-tahini.",
      "Garnir le pain avec poulet, crudités et sauce.",
    ],
    ingredients: [
      { name: "Filet de poulet", qtyPerPerson: 140, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Pain pita", qtyPerPerson: 1, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.55 },
      { name: "Yaourt nature", qtyPerPerson: 50, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.004 },
      { name: "Tomate", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
    ],
  },
  {
    id: "nouilles-sautees",
    name: "Nouilles sautées aux légumes",
    cookName: "Malee",
    emoji: "🍜",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 20,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: ["gluten", "soja", "sesame"],
    tags: ["asiatique", "healthy", "street-food"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Cuire les nouilles.",
      "Sauter poivron, carotte et chou à feu vif.",
      "Mélanger avec les nouilles et la sauce soja.",
    ],
    ingredients: [
      { name: "Nouilles chinoises", qtyPerPerson: 90, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.003 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Carotte", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Sauce soja", qtyPerPerson: 15, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.004 },
    ],
  },

  // -------------------- Desserts & goûter --------------------
  {
    id: "tarte-tatin",
    name: "Tarte tatin aux pommes",
    cookName: "Mamie Jeanne",
    emoji: "🥧",
    moments: ["dessert", "gouter"],
    level: 3,
    timeMin: 50,
    equipment: ["four", "poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["francais", "gourmand", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Caraméliser les pommes avec sucre et beurre.",
      "Recouvrir de pâte feuilletée.",
      "Cuire 30 min à 180°C puis retourner.",
    ],
    ingredients: [
      { name: "Pomme", qtyPerPerson: 1.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
      { name: "Pâte feuilletée", qtyPerPerson: 0.25, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 1.5 },
      { name: "Sucre", qtyPerPerson: 25, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
      { name: "Beurre", qtyPerPerson: 20, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
    ],
  },
  {
    id: "fondant-chocolat",
    name: "Fondant au chocolat",
    cookName: "Antoine",
    emoji: "🍫",
    moments: ["dessert", "gouter"],
    level: 2,
    timeMin: 25,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Fondre chocolat et beurre.",
      "Ajouter sucre, œufs et un peu de farine.",
      "Cuire 10 min à 200°C : cœur coulant.",
    ],
    ingredients: [
      { name: "Chocolat noir", qtyPerPerson: 50, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.012 },
      { name: "Beurre", qtyPerPerson: 30, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Sucre", qtyPerPerson: 20, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
    ],
  },
  {
    id: "tiramisu",
    name: "Tiramisu café-mascarpone",
    cookName: "Giulia",
    emoji: "☕",
    moments: ["dessert"],
    level: 2,
    timeMin: 30,
    equipment: [],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["italien", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Fouetter jaunes, sucre et mascarpone, incorporer les blancs.",
      "Tremper les biscuits dans le café.",
      "Monter en couches, réserver 4 h au frais, cacao dessus.",
    ],
    ingredients: [
      { name: "Mascarpone", qtyPerPerson: 80, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.011 },
      { name: "Biscuits cuillère", qtyPerPerson: 50, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.008 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Café", qtyPerPerson: 50, unit: "ml", aisle: "Épicerie sucrée", unitPrice: 0.004 },
    ],
  },
  {
    id: "riz-au-lait",
    name: "Riz au lait vanillé",
    cookName: "Mamie Jeanne",
    emoji: "🍮",
    moments: ["dessert", "gouter"],
    level: 1,
    timeMin: 35,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["francais", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Cuire le riz rond doucement dans le lait sucré.",
      "Remuer souvent jusqu'à texture crémeuse.",
      "Parfumer à la vanille.",
    ],
    ingredients: [
      { name: "Riz rond", qtyPerPerson: 50, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Lait", qtyPerPerson: 250, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Sucre", qtyPerPerson: 20, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
    ],
  },
  {
    id: "crepes",
    name: "Crêpes sucrées",
    cookName: "Erwan",
    emoji: "🥞",
    moments: ["gouter", "dessert", "petit-dej"],
    level: 1,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "gourmand", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Mélanger farine, œufs, lait et une pincée de sel.",
      "Laisser reposer la pâte 30 min.",
      "Cuire de fines crêpes à la poêle.",
    ],
    ingredients: [
      { name: "Farine", qtyPerPerson: 60, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Lait", qtyPerPerson: 150, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
    ],
  },
  {
    id: "banana-bread",
    name: "Banana bread",
    cookName: "Emma",
    emoji: "🍌",
    moments: ["gouter", "petit-dej", "dessert"],
    level: 1,
    timeMin: 55,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["americain", "gourmand", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Écraser les bananes bien mûres.",
      "Mélanger avec œufs, sucre, beurre et farine.",
      "Cuire 45 min à 170°C en moule à cake.",
    ],
    ingredients: [
      { name: "Banane", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Farine", qtyPerPerson: 45, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Œuf", qtyPerPerson: 0.5, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Sucre", qtyPerPerson: 25, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
      { name: "Beurre", qtyPerPerson: 20, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
    ],
  },
  {
    id: "salade-fruits",
    name: "Salade de fruits frais",
    cookName: "Inès",
    emoji: "🍉",
    moments: ["dessert", "gouter", "brunch"],
    level: 1,
    timeMin: 15,
    equipment: [],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["healthy"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Couper les fruits de saison en morceaux.",
      "Arroser d'un peu de jus de citron.",
      "Réserver au frais avant de servir.",
    ],
    ingredients: [
      { name: "Pomme", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
      { name: "Banane", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Orange", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.4 },
      { name: "Citron", qtyPerPerson: 0.2, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
    ],
  },
  {
    id: "gaufres",
    name: "Gaufres croustillantes",
    cookName: "Sarah",
    emoji: "🧇",
    moments: ["gouter", "dessert", "petit-dej"],
    level: 1,
    timeMin: 25,
    equipment: [],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["gourmand", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Préparer une pâte à gaufres lisse.",
      "Cuire au gaufrier jusqu'à dorure.",
      "Saupoudrer de sucre glace.",
    ],
    ingredients: [
      { name: "Farine", qtyPerPerson: 60, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Œuf", qtyPerPerson: 0.75, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Lait", qtyPerPerson: 120, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Beurre", qtyPerPerson: 20, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
    ],
  },
  {
    id: "clafoutis",
    name: "Clafoutis aux cerises",
    cookName: "Sylvie",
    emoji: "🍒",
    moments: ["dessert", "gouter"],
    level: 1,
    timeMin: 45,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "gourmand", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Disposer les cerises dans un plat beurré.",
      "Verser l'appareil œufs-lait-farine-sucre.",
      "Cuire 35 min à 180°C.",
    ],
    ingredients: [
      { name: "Cerises", qtyPerPerson: 120, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.006 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Lait", qtyPerPerson: 100, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Farine", qtyPerPerson: 30, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
    ],
  },
];
