import type { Recipe } from "./types";
import { EXTRA_RECIPES } from "./recipes-extra";

// ============================================================
// Popote — Base de recettes curées (écrites par des humains)
// Prix : € par unité de base (g, ml, pièce). Visée : 1–5 €/pers.
// NB : catalogue = 79 recettes signées, CHACUNE avec sa photo unique
// (voir lib/photos.ts). Les recettes générées par modèles ont été
// retirées : impossible de leur donner une photo unique et exacte.
// ============================================================

const CORE_RECIPES: Recipe[] = [
  {
    id: "carbonara",
    name: "Vraies pâtes carbonara",
    cookName: "Giulia",
    emoji: "🍝",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 20,
    equipment: ["casserole", "poele"],
    isMeat: true,
    isFish: false,
    hasPork: true,
    isVegan: false,
    allergens: ["gluten", "oeuf", "lactose"],
    tags: ["italien", "reconfort", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Faire cuire les spaghetti al dente dans une grande casserole d'eau salée.",
      "Faire revenir les lardons (guanciale) dans une poêle sans matière grasse.",
      "Battre les jaunes d'œuf avec le pecorino râpé et du poivre.",
      "Hors du feu, mélanger pâtes égouttées, lardons puis l'appareil aux œufs.",
      "Détendre avec un peu d'eau de cuisson jusqu'à obtenir une crème lisse.",
    ],
    ingredients: [
      { name: "Spaghetti", qtyPerPerson: 110, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.0018 },
      { name: "Guanciale (ou lardons)", qtyPerPerson: 60, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.018 },
      { name: "Jaune d'œuf", qtyPerPerson: 1.5, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Pecorino râpé", qtyPerPerson: 30, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.03 },
    ],
  },
  {
    id: "burger-maison",
    name: "Burger maison boeuf-cheddar",
    cookName: "Marc",
    emoji: "🍔",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 2,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "moutarde", "sesame"],
    tags: ["americain", "street-food", "gourmand", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Former des steaks de bœuf haché, saler et poivrer.",
      "Snacker 2 min par face dans une poêle bien chaude, poser le cheddar.",
      "Toaster les pains, tartiner sauce (mayo-moutarde-ketchup).",
      "Monter avec salade, tomate, oignon rouge et le steak.",
    ],
    ingredients: [
      { name: "Pain à burger", qtyPerPerson: 1, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.5 },
      { name: "Steak haché de bœuf", qtyPerPerson: 130, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.013 },
      { name: "Cheddar en tranche", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.35 },
      { name: "Tomate", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Salade", qtyPerPerson: 0.2, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 1.1 },
      { name: "Oignon rouge", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.4 },
    ],
  },
  {
    id: "kebab-maison",
    name: "Kebab de poulet maison",
    cookName: "Yassine",
    emoji: "🌯",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 1,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "sesame"],
    tags: ["oriental", "street-food", "reconfort", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Émincer le poulet, mariner avec cumin, paprika, ail et huile.",
      "Saisir à la poêle bien chaude jusqu'à coloration.",
      "Préparer la sauce blanche (yaourt, citron, ail).",
      "Garnir le pain pita : poulet, crudités, sauce.",
    ],
    ingredients: [
      { name: "Filet de poulet", qtyPerPerson: 140, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Pain pita", qtyPerPerson: 1, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.55 },
      { name: "Yaourt nature", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.004 },
      { name: "Tomate", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Oignon", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Salade", qtyPerPerson: 0.15, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 1.1 },
    ],
  },
  {
    id: "tacos-poulet",
    name: "Tacos français poulet-fromage",
    cookName: "Sofiane",
    emoji: "🌮",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 1,
    timeMin: 28,
    equipment: ["poele"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["street-food", "reconfort", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Poêler le poulet émincé avec épices tacos.",
      "Préparer une sauce fromagère (crème + fromage fondu).",
      "Garnir la galette : frites, poulet, sauce fromagère.",
      "Plier et faire dorer au grill/poêle.",
    ],
    ingredients: [
      { name: "Galette de blé (wrap)", qtyPerPerson: 1, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.5 },
      { name: "Filet de poulet", qtyPerPerson: 120, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Frites surgelées", qtyPerPerson: 90, unit: "g", aisle: "Surgelés", unitPrice: 0.003 },
      { name: "Crème fraîche", qtyPerPerson: 40, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.006 },
      { name: "Fromage râpé", qtyPerPerson: 40, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
    ],
  },
  {
    id: "ravioles-cremeuses",
    name: "Ravioles crémeuses aux herbes",
    cookName: "Camille",
    emoji: "🥟",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 12,
    equipment: ["casserole", "poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "reconfort", "italien"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Pocher les ravioles 2 min dans l'eau frémissante.",
      "Faire chauffer la crème avec l'ail et les herbes.",
      "Mélanger délicatement, parsemer de parmesan et de ciboulette.",
    ],
    ingredients: [
      { name: "Ravioles du Dauphiné", qtyPerPerson: 150, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.012 },
      { name: "Crème fraîche", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.006 },
      { name: "Parmesan râpé", qtyPerPerson: 20, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.035 },
      { name: "Ciboulette", qtyPerPerson: 5, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.05 },
    ],
  },
  {
    id: "curry-legumes",
    name: "Curry de légumes coco",
    cookName: "Priya",
    emoji: "🍛",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 30,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["indien", "healthy", "epice", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Faire revenir oignon, ail et gingembre.",
      "Ajouter les épices puis les légumes en dés.",
      "Verser le lait de coco, mijoter 20 min.",
      "Servir avec du riz basmati.",
    ],
    ingredients: [
      { name: "Lait de coco", qtyPerPerson: 100, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Patate douce", qtyPerPerson: 120, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0025 },
      { name: "Pois chiches", qtyPerPerson: 80, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Riz basmati", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Pâte de curry", qtyPerPerson: 15, unit: "g", aisle: "Épicerie salée", unitPrice: 0.015 },
    ],
  },
  {
    id: "poke-bowl-saumon",
    name: "Poke bowl saumon-avocat",
    cookName: "Léa",
    emoji: "🥗",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 20,
    equipment: ["casserole"],
    isMeat: false,
    isFish: true,
    hasPork: false,
    isVegan: false,
    allergens: ["poisson", "soja", "sesame"],
    tags: ["asiatique", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Cuire le riz et le laisser tiédir.",
      "Couper le saumon en cubes, mariner sauce soja + sésame.",
      "Dresser riz, saumon, avocat, edamame, concombre.",
      "Arroser de sauce et parsemer de graines de sésame.",
    ],
    ingredients: [
      { name: "Pavé de saumon", qtyPerPerson: 110, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.022 },
      { name: "Riz rond", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Avocat", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.9 },
      { name: "Edamame", qtyPerPerson: 40, unit: "g", aisle: "Surgelés", unitPrice: 0.006 },
      { name: "Concombre", qtyPerPerson: 0.25, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Sauce soja", qtyPerPerson: 15, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.004 },
    ],
  },
  {
    id: "houmous-apero",
    name: "Houmous maison & crudités",
    cookName: "Nadia",
    emoji: "🫓",
    moments: ["apero", "afterwork"],
    level: 1,
    timeMin: 10,
    equipment: ["robot"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: ["sesame"],
    tags: ["oriental", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Mixer pois chiches, tahini, ail, citron et huile d'olive.",
      "Détendre avec un peu d'eau, saler.",
      "Servir avec bâtonnets de légumes et pain pita.",
    ],
    ingredients: [
      { name: "Pois chiches", qtyPerPerson: 90, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Tahini (purée de sésame)", qtyPerPerson: 15, unit: "g", aisle: "Épicerie salée", unitPrice: 0.012 },
      { name: "Citron", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
      { name: "Carotte", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.2 },
      { name: "Concombre", qtyPerPerson: 0.25, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
    ],
  },
  {
    id: "crumble-pommes",
    name: "Crumble pommes-cannelle",
    cookName: "Mamie Jeanne",
    emoji: "🍎",
    moments: ["dessert", "gouter"],
    level: 1,
    timeMin: 40,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["francais", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Éplucher et couper les pommes, disposer dans un plat.",
      "Sabler farine, beurre, sucre du bout des doigts.",
      "Recouvrir les pommes, enfourner 30 min à 180°C.",
    ],
    ingredients: [
      { name: "Pomme", qtyPerPerson: 1.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.35 },
      { name: "Farine", qtyPerPerson: 40, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Beurre", qtyPerPerson: 30, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
      { name: "Sucre", qtyPerPerson: 25, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
    ],
  },
  {
    id: "pancakes",
    name: "Pancakes moelleux du dimanche",
    cookName: "Emma",
    emoji: "🥞",
    moments: ["petit-dej", "brunch", "gouter"],
    level: 1,
    timeMin: 20,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["americain", "gourmand", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Mélanger farine, levure, sucre, œuf et lait.",
      "Cuire de petites louches dans une poêle beurrée.",
      "Retourner quand des bulles apparaissent, servir avec du sirop.",
    ],
    ingredients: [
      { name: "Farine", qtyPerPerson: 60, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Lait", qtyPerPerson: 100, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
      { name: "Œuf", qtyPerPerson: 0.5, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Sucre", qtyPerPerson: 15, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
    ],
  },
  {
    id: "oeufs-brouilles-avocado",
    name: "Œufs brouillés & avocado toast",
    cookName: "Tom",
    emoji: "🍳",
    moments: ["petit-dej", "brunch"],
    level: 1,
    timeMin: 12,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "oeuf", "lactose"],
    tags: ["healthy", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Écraser l'avocat sur le pain toasté, citron et sel.",
      "Brouiller les œufs à feu doux avec une noix de beurre.",
      "Dresser les œufs sur le toast, poivrer.",
    ],
    ingredients: [
      { name: "Œuf", qtyPerPerson: 2, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Pain de campagne", qtyPerPerson: 80, unit: "g", aisle: "Boulangerie", unitPrice: 0.004 },
      { name: "Avocat", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.9 },
    ],
  },
  {
    id: "salade-cesar",
    name: "Salade César au poulet grillé",
    cookName: "Chloé",
    emoji: "🥬",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 25,
    equipment: ["poele", "four"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf", "moutarde", "poisson"],
    tags: ["americain", "healthy"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Griller le poulet et le trancher.",
      "Préparer la sauce César (parmesan, moutarde, anchois, huile).",
      "Mélanger salade, croûtons, poulet et sauce.",
    ],
    ingredients: [
      { name: "Filet de poulet", qtyPerPerson: 110, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Salade romaine", qtyPerPerson: 0.4, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 1.2 },
      { name: "Parmesan râpé", qtyPerPerson: 20, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.035 },
      { name: "Pain (croûtons)", qtyPerPerson: 40, unit: "g", aisle: "Boulangerie", unitPrice: 0.004 },
    ],
  },
  {
    id: "chili-sin-carne",
    name: "Chili sin carne haricots rouges",
    cookName: "Diego",
    emoji: "🌶️",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 30,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["mexicain", "epice", "healthy", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Revenir oignon, poivron et ail.",
      "Ajouter haricots rouges, maïs, tomates et épices.",
      "Mijoter 20 min, servir avec du riz.",
    ],
    ingredients: [
      { name: "Haricots rouges", qtyPerPerson: 100, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Tomates concassées", qtyPerPerson: 120, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Maïs", qtyPerPerson: 40, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Riz", qtyPerPerson: 60, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.002 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "pad-thai",
    name: "Pad thaï aux crevettes",
    cookName: "Malee",
    emoji: "🍤",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 25,
    equipment: ["poele"],
    isMeat: false,
    isFish: true,
    hasPork: false,
    isVegan: false,
    allergens: ["fruits-de-mer", "oeuf", "arachide", "soja"],
    tags: ["asiatique", "street-food", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Réhydrater les nouilles de riz.",
      "Sauter crevettes, œuf, puis nouilles et sauce pad thaï.",
      "Ajouter pousses de soja, cacahuètes et citron vert.",
    ],
    ingredients: [
      { name: "Nouilles de riz", qtyPerPerson: 80, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.004 },
      { name: "Crevettes", qtyPerPerson: 90, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.02 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Cacahuètes", qtyPerPerson: 20, unit: "g", aisle: "Épicerie salée", unitPrice: 0.008 },
      { name: "Sauce soja", qtyPerPerson: 15, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.004 },
    ],
  },
  {
    id: "risotto-champignons",
    name: "Risotto crémeux aux champignons",
    cookName: "Paolo",
    emoji: "🍄",
    moments: ["dejeuner", "diner"],
    level: 3,
    timeMin: 35,
    equipment: ["casserole", "poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["italien", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Faire revenir les champignons, réserver.",
      "Nacrer le riz, déglacer au vin blanc.",
      "Ajouter le bouillon louche par louche en remuant.",
      "Terminer avec parmesan, beurre et champignons.",
    ],
    ingredients: [
      { name: "Riz arborio", qtyPerPerson: 80, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.003 },
      { name: "Champignons de Paris", qtyPerPerson: 120, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.005 },
      { name: "Parmesan râpé", qtyPerPerson: 25, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.035 },
      { name: "Bouillon de légumes", qtyPerPerson: 250, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.0008 },
    ],
  },
  {
    id: "quiche-lorraine",
    name: "Quiche lorraine",
    cookName: "Bernard",
    emoji: "🥧",
    moments: ["dejeuner", "diner", "brunch"],
    level: 2,
    timeMin: 45,
    equipment: ["four"],
    isMeat: true,
    isFish: false,
    hasPork: true,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["francais", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Étaler la pâte dans un moule, piquer le fond.",
      "Répartir les lardons.",
      "Verser l'appareil œufs-crème-lait, enfourner 35 min à 180°C.",
    ],
    ingredients: [
      { name: "Pâte brisée", qtyPerPerson: 0.3, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 1.4 },
      { name: "Lardons", qtyPerPerson: 50, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.012 },
      { name: "Œuf", qtyPerPerson: 1, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Crème fraîche", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.006 },
    ],
  },
  {
    id: "dahl-lentilles",
    name: "Dahl de lentilles corail",
    cookName: "Aarav",
    emoji: "🍲",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 30,
    equipment: ["casserole"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["indien", "healthy", "epice", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Faire revenir oignon, ail, gingembre et épices.",
      "Ajouter lentilles corail et lait de coco.",
      "Mijoter 20 min jusqu'à texture fondante.",
    ],
    ingredients: [
      { name: "Lentilles corail", qtyPerPerson: 80, unit: "g", aisle: "Épicerie salée", unitPrice: 0.004 },
      { name: "Lait de coco", qtyPerPerson: 80, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Tomates concassées", qtyPerPerson: 80, unit: "g", aisle: "Épicerie salée", unitPrice: 0.0018 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "gratin-dauphinois",
    name: "Gratin dauphinois",
    cookName: "Mamie Jeanne",
    emoji: "🥔",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 60,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["lactose"],
    tags: ["francais", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Émincer finement les pommes de terre.",
      "Disposer en couches, verser crème et lait à l'ail.",
      "Enfourner 50 min à 170°C.",
    ],
    ingredients: [
      { name: "Pomme de terre", qtyPerPerson: 250, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
      { name: "Crème fraîche", qtyPerPerson: 80, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.006 },
      { name: "Lait", qtyPerPerson: 80, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
    ],
  },
  {
    id: "wrap-vege",
    name: "Wrap végé falafel",
    cookName: "Yara",
    emoji: "🥙",
    moments: ["dejeuner", "afterwork"],
    level: 1,
    timeMin: 15,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: ["gluten", "sesame"],
    tags: ["oriental", "street-food", "healthy"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Réchauffer les falafels.",
      "Garnir la galette de houmous, falafels, crudités.",
      "Rouler serré et couper en deux.",
    ],
    ingredients: [
      { name: "Galette de blé (wrap)", qtyPerPerson: 1, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.5 },
      { name: "Falafels", qtyPerPerson: 90, unit: "g", aisle: "Surgelés", unitPrice: 0.008 },
      { name: "Tomate", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.45 },
      { name: "Salade", qtyPerPerson: 0.15, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 1.1 },
    ],
  },
  {
    id: "soupe-potiron",
    name: "Velouté de potiron",
    cookName: "Sylvie",
    emoji: "🎃",
    moments: ["diner", "dejeuner"],
    level: 1,
    timeMin: 30,
    equipment: ["casserole", "robot"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["francais", "healthy", "reconfort"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Couper le potiron et la pomme de terre en dés.",
      "Cuire dans le bouillon 20 min.",
      "Mixer finement, ajuster l'assaisonnement.",
    ],
    ingredients: [
      { name: "Potiron", qtyPerPerson: 300, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0018 },
      { name: "Pomme de terre", qtyPerPerson: 80, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Bouillon de légumes", qtyPerPerson: 300, unit: "ml", aisle: "Épicerie salée", unitPrice: 0.0008 },
    ],
  },
  {
    id: "saumon-four-legumes",
    name: "Saumon rôti & légumes du soleil",
    cookName: "Hélène",
    emoji: "🐟",
    moments: ["dejeuner", "diner"],
    level: 2,
    timeMin: 30,
    equipment: ["four"],
    isMeat: false,
    isFish: true,
    hasPork: false,
    isVegan: false,
    allergens: ["poisson"],
    tags: ["healthy", "francais"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Couper courgette et poivron, arroser d'huile d'olive.",
      "Poser les pavés de saumon, assaisonner.",
      "Enfourner 20 min à 190°C.",
    ],
    ingredients: [
      { name: "Pavé de saumon", qtyPerPerson: 120, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.022 },
      { name: "Courgette", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.7 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Pomme de terre", qtyPerPerson: 150, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
    ],
  },
  {
    id: "pizza-margherita",
    name: "Pizza margherita maison",
    cookName: "Enzo",
    emoji: "🍕",
    moments: ["dejeuner", "diner", "afterwork"],
    level: 2,
    timeMin: 40,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["italien", "reconfort", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Étaler la pâte à pizza.",
      "Napper de sauce tomate, ajouter la mozzarella.",
      "Cuire 12 min à 240°C, basilic frais à la sortie.",
    ],
    ingredients: [
      { name: "Pâte à pizza", qtyPerPerson: 0.5, unit: "pièce", aisle: "Boulangerie", unitPrice: 1.2 },
      { name: "Sauce tomate", qtyPerPerson: 60, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Mozzarella", qtyPerPerson: 60, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
      { name: "Basilic", qtyPerPerson: 5, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.06 },
    ],
  },
  {
    id: "buddha-bowl",
    name: "Buddha bowl quinoa-légumes rôtis",
    cookName: "Manon",
    emoji: "🥦",
    moments: ["dejeuner", "diner"],
    level: 1,
    timeMin: 30,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["healthy", "francais"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Rôtir patate douce et pois chiches au four.",
      "Cuire le quinoa.",
      "Dresser le bol avec avocat et sauce tahini.",
    ],
    ingredients: [
      { name: "Quinoa", qtyPerPerson: 70, unit: "g", aisle: "Pâtes, riz & féculents", unitPrice: 0.006 },
      { name: "Patate douce", qtyPerPerson: 150, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0025 },
      { name: "Pois chiches", qtyPerPerson: 80, unit: "g", aisle: "Épicerie salée", unitPrice: 0.003 },
      { name: "Avocat", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.9 },
    ],
  },
  {
    id: "croque-monsieur",
    name: "Croque-monsieur gratiné",
    cookName: "Julien",
    emoji: "🧀",
    moments: ["dejeuner", "gouter", "afterwork"],
    level: 1,
    timeMin: 15,
    equipment: ["four", "poele"],
    isMeat: true,
    isFish: false,
    hasPork: true,
    isVegan: false,
    allergens: ["gluten", "lactose"],
    tags: ["francais", "reconfort", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Beurrer le pain de mie, garnir jambon + fromage.",
      "Napper de béchamel express, parsemer de gruyère.",
      "Gratiner 8 min au four.",
    ],
    ingredients: [
      { name: "Pain de mie", qtyPerPerson: 2, unit: "pièce", aisle: "Boulangerie", unitPrice: 0.18 },
      { name: "Jambon", qtyPerPerson: 1, unit: "pièce", aisle: "Boucherie & poissonnerie", unitPrice: 0.7 },
      { name: "Fromage râpé", qtyPerPerson: 50, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.012 },
      { name: "Lait", qtyPerPerson: 50, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.0011 },
    ],
  },
  {
    id: "smoothie-bowl",
    name: "Smoothie bowl banane-fruits rouges",
    cookName: "Inès",
    emoji: "🍓",
    moments: ["petit-dej", "gouter", "brunch"],
    level: 1,
    timeMin: 8,
    equipment: ["robot"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: [],
    tags: ["healthy", "gourmand"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Mixer banane congelée, fruits rouges et boisson végétale.",
      "Verser dans un bol.",
      "Garnir de flocons d'avoine et fruits frais.",
    ],
    ingredients: [
      { name: "Banane", qtyPerPerson: 1, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Fruits rouges surgelés", qtyPerPerson: 80, unit: "g", aisle: "Surgelés", unitPrice: 0.006 },
      { name: "Flocons d'avoine", qtyPerPerson: 30, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.003 },
      { name: "Boisson d'avoine", qtyPerPerson: 100, unit: "ml", aisle: "Crémerie & œufs", unitPrice: 0.002 },
    ],
  },
  {
    id: "cookies",
    name: "Cookies pépites de chocolat",
    cookName: "Sarah",
    emoji: "🍪",
    moments: ["gouter", "dessert"],
    level: 1,
    timeMin: 25,
    equipment: ["four"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["gluten", "lactose", "oeuf"],
    tags: ["americain", "gourmand", "reconfort"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Crémer beurre et sucre, ajouter l'œuf.",
      "Incorporer farine, levure et pépites.",
      "Former des boules, cuire 11 min à 180°C.",
    ],
    ingredients: [
      { name: "Farine", qtyPerPerson: 45, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0015 },
      { name: "Beurre", qtyPerPerson: 25, unit: "g", aisle: "Crémerie & œufs", unitPrice: 0.009 },
      { name: "Sucre", qtyPerPerson: 25, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
      { name: "Pépites de chocolat", qtyPerPerson: 30, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.008 },
      { name: "Œuf", qtyPerPerson: 0.25, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
    ],
  },
  {
    id: "brochettes-bbq",
    name: "Brochettes de poulet mariné BBQ",
    cookName: "Karim",
    emoji: "🍢",
    moments: ["dejeuner", "diner", "apero"],
    level: 2,
    timeMin: 30,
    equipment: ["barbecue"],
    isMeat: true,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["moutarde"],
    tags: ["americain", "street-food", "epice"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Mariner le poulet (huile, paprika, ail, miel, moutarde).",
      "Monter les brochettes avec poivron et oignon.",
      "Griller au barbecue en tournant régulièrement.",
    ],
    ingredients: [
      { name: "Filet de poulet", qtyPerPerson: 150, unit: "g", aisle: "Boucherie & poissonnerie", unitPrice: 0.011 },
      { name: "Poivron", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.8 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
      { name: "Miel", qtyPerPerson: 10, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.008 },
    ],
  },
  {
    id: "mousse-chocolat",
    name: "Mousse au chocolat",
    cookName: "Antoine",
    emoji: "🍫",
    moments: ["dessert"],
    level: 2,
    timeMin: 20,
    equipment: ["robot"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf", "lactose"],
    tags: ["francais", "gourmand"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Fondre le chocolat au bain-marie.",
      "Incorporer les jaunes, puis les blancs montés en neige.",
      "Réserver au frais 3 h minimum.",
    ],
    ingredients: [
      { name: "Chocolat noir", qtyPerPerson: 50, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.012 },
      { name: "Œuf", qtyPerPerson: 1.5, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Sucre", qtyPerPerson: 15, unit: "g", aisle: "Épicerie sucrée", unitPrice: 0.0012 },
    ],
  },
  {
    id: "tortilla-espagnole",
    name: "Tortilla espagnole pommes de terre",
    cookName: "Lucia",
    emoji: "🥘",
    moments: ["dejeuner", "diner", "apero", "afterwork"],
    level: 2,
    timeMin: 35,
    equipment: ["poele"],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: false,
    allergens: ["oeuf"],
    tags: ["reconfort", "healthy"],
    isLocal: true,
    isSeasonal: true,
    steps: [
      "Cuire doucement les pommes de terre et l'oignon à l'huile.",
      "Mélanger aux œufs battus.",
      "Cuire la tortilla à la poêle, retourner à mi-cuisson.",
    ],
    ingredients: [
      { name: "Pomme de terre", qtyPerPerson: 200, unit: "g", aisle: "Fruits & légumes", unitPrice: 0.0015 },
      { name: "Œuf", qtyPerPerson: 2, unit: "pièce", aisle: "Crémerie & œufs", unitPrice: 0.3 },
      { name: "Oignon", qtyPerPerson: 0.5, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
  {
    id: "guacamole-nachos",
    name: "Guacamole & nachos",
    cookName: "Diego",
    emoji: "🥑",
    moments: ["apero", "afterwork"],
    level: 1,
    timeMin: 10,
    equipment: [],
    isMeat: false,
    isFish: false,
    hasPork: false,
    isVegan: true,
    allergens: ["gluten"],
    tags: ["mexicain", "street-food", "epice"],
    isLocal: false,
    isSeasonal: true,
    steps: [
      "Écraser l'avocat avec citron vert, oignon et coriandre.",
      "Assaisonner, ajouter un peu de piment.",
      "Servir avec les chips tortilla.",
    ],
    ingredients: [
      { name: "Avocat", qtyPerPerson: 0.75, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.9 },
      { name: "Citron vert", qtyPerPerson: 0.3, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.4 },
      { name: "Chips tortilla", qtyPerPerson: 40, unit: "g", aisle: "Épicerie salée", unitPrice: 0.006 },
      { name: "Oignon", qtyPerPerson: 0.25, unit: "pièce", aisle: "Fruits & légumes", unitPrice: 0.3 },
    ],
  },
];

// Recettes "fait maison" signées (cœur éditorial de Popote).
export const SIGNED_RECIPES: Recipe[] = [...CORE_RECIPES, ...EXTRA_RECIPES];

// Catalogue = uniquement les recettes signées, chacune avec sa photo unique.
export const RECIPES: Recipe[] = SIGNED_RECIPES;
